name: Testing ReusableWorkflow00
on: 
  push:
    branches: 
      - main
    paths:
      - 'muleapp/**'

jobs:
    call-workflow-passing-data:
      uses: nachoborente/PublicPipelineSharedLibrary/.github/workflows/ReusableWorkflow00.yml@main
      with:
        testvar: 'hello world, calling to ReusableWorkflow00'
      secrets: inherit