name: Testing MavenWorkflow
on: 
  push:
    branches: 
      - main
    paths:
      - 'muleapp/**'

jobs:
    call-workflow-passing-data:
      uses: nachoborente/PublicPipelineSharedLibrary/.github/workflows/mavenworkflow01.yml@main
      with:
        testvar: 'hello world, calling to mavenworkflow01, test01'
      secrets: inherit