name: Deploy Lambda Function
on: [push]

jobs:
    call-workflow-passing-data:
      uses: nachoborente/PublicPipelineSharedLibrary/.github/workflows/ReusableWorkflow00.yml@main
      with:
        testvar: 'hello from the other side'
      secrets: inherit